#!/bin/bash
# while read line
# do
#   # break if the line is empty
#   [ -z "$line" ] && break
#   echo $line >> note
# done

# var=$(</dev/stdin)
# echo "$var" >> note

echo 'Enter one line at a time'
echo 'Press CTRL+D to finish'
cat >> testoutput
echo 'OK'